### ISSUE TITLE
New database structure for client and server sides

### ISSUE THREAD

**Issue by DK404-main** [DK404-main/Sofen#1]
# Database server:
![database-server-side](https://github.com/user-attachments/assets/08c9d774-ac56-431d-81d2-63298036cd8a)

# Database client:
![database-client-side](https://github.com/user-attachments/assets/28690002-a920-419b-bbc0-c9aef27c2f52)

**Comment by MikaCat2008** [comment]
3 часа ночи сноу кодит, я вахуе блять

**Comment by DK404-main** [comment]
> 3 часа ночи сноу кодит, я вахуе блять

Yes, I`m)
